name: Compile Kotlin code

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Kotlin
        run: sudo apt-get update && sudo apt-get install -y kotlin

      - name: Compile All Kotlin Files
        run: make -j$(nproc)
